USE [DBMINC]
GO

/* 
 * TABLE: CORPORATIVO.S_PESSOA_FISICA 
 */
ALTER TABLE CORPORATIVO.S_PESSOA_FISICA
  ADD DS_NACIONALIDADE VARCHAR(200);
GO

ALTER TABLE CORPORATIVO.S_PESSOA_FISICA
  ADD DS_FATOR_RH VARCHAR(10);
GO

/* 
 * TABLE: CORPORATIVO.S_DOCUMENTACAO_PESSOA 
 */
-- ADIÇÃO DE CAMPO DE DATA DE EXPERDIÇÃO DO REGISTRO PROFISSIONAL
ALTER TABLE CORPORATIVO.S_DOCUMENTACAO_PESSOA ADD DT_EXP_CONSELHO_CLASSE DATE
GO

ALTER TABLE CORPORATIVO.S_DOCUMENTACAO_PESSOA ADD SG_UF_CERT_RESERVISTA CHAR(2)
GO

ALTER TABLE CORPORATIVO.S_DOCUMENTACAO_PESSOA ADD CONSTRAINT FK_S_DOCUMENTACAO_PESSOA_S_UF_CERT_RESERVISTA
    FOREIGN KEY (SG_UF_CERT_RESERVISTA)
    REFERENCES CORPORATIVO.S_UF(SG_UF)
GO 

/* 
 * TABLE: CORPORATIVO.S_PESSOA_ESTRANGEIRA 
 */
ALTER TABLE CORPORATIVO.S_PESSOA_ESTRANGEIRA ADD DT_CHEGADA_BRASIL DATE
GO

ALTER TABLE CORPORATIVO.S_PESSOA_ESTRANGEIRA ADD DT_NATURALIZACAO DATE
GO
